mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='root/')),
    url(r'^root/', include('root.urls', namespace='root')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^admin/', admin.site.urls),
    url(r'^surveys/', include('surveys.urls', namespace='surveys')),
]

mysite/polls/urls.py
from django.conf.urls import url

# . means current directory
from . import views

# Have to be careful with app_name, this allows to change the app's namespace!
# It also doesn't seem to be needed? -> Check with Maddy
#app_name = 'surveys'
app_name = 'polls'

urlpatterns = [
    # 127.0.0.1/polls
    url(r'^$', views.index, name='index'),

    # 127.0.0.1/polls/1
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),

    # # if we call this url by name, we jst need to change it here
    # # without updating the templates, and the new URL will work!
    # # 127.0.0.1/polls/question/1
    # url(r'^question/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),

    # 127.0.0.1/polls/1/results
    url(r'^(?P<question_id>[0-9]+)/results$', views.results, name='results'),

    # 127.0.0.1/polls/1/vote
    url(r'^(?P<question_id>[0-9]+)/vote$', views.vote, name='vote'),
        ]

mysite/root/urls.py
from django.conf.urls import url

# . means current directory
from . import views

urlpatterns = [
    # 127.0.0.1/
    url('^$', views.root_index, name='index')
    ]

mysite/surveys/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index')
    ]

mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Date Published')

    def __str__(self):
        return self.question_text

    def recently_added(self):
            return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

    def is_polular(self):
        return self.votes >= 5

mysite/surveys/models.py
from django.db import models


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(name='Question', max_length=200)
    pub_date = models.DateTimeField('Date Posted')

    def __str__(self):
        # As the name will be used as a column, have to use it for this method
        return self.Question


class Answer(models.Model):
    answer_text = models.CharField(name='Answer', max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        # As the name will be used as a column, have to use it for this method
        return self.Answer

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect

from django.template import loader
from django.shortcuts import render, Http404, get_object_or_404
from django.core.urlresolvers import reverse
from .models import Question
# Create your views here.

def index(request):
    latest_questions = Question.objects.order_by('pub_date')[:5]

    # The short version! - using the 'render'shortcut
    context = {'latest_questions': latest_questions}
    # here is the right order of arguments for the render function
    return render(request, 'polls/index.html', context)

    # # The long version!!
    # template = loader.get_template('polls/index.html')
    # context = {
    #     'latest_questions': latest_questions
    # }
    # return HttpResponse(template.render(context, request))

    # Playing around
    # welcome_msg = '<h3>Welcome to the polls app!</h3><h5>Here are the latest questions:</h5>'
    # output = '<br>'.join(q.question_text for q in latest_questions)
    # return HttpResponse('<h1>Hello and welcome. You\'re at the polls index.<h1>')


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except:
        raise Http404("The question with ID {} does not exist".format(question_id))
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        # request.POST is a dictionary-like object that lets you access submitted data by key name
        # this will return the ID of the selected choice as a string
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except:
            return render(request, 'polls/detail.html', {'question': question, 'error_message': 'Please select one of the available choices'})
    else:
        selected_choice.votes += 1
        selected_choice.save()

    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.

    # must have a comma if you pass just one argument
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/root/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

def root_index(request):
    # return HttpResponse('<h3>You are at the root dir<h3>')
    return render(request, 'root/index.html')

mysite/surveys/views.py
from django.http import HttpResponse

def index(request):
    return HttpResponse('<h3>Hello and welcome to the surveys app!<h3>')

mysite/polls/templates/polls/base.html
{%  load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Polls</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/bootstrap/css/bootstrap.min.css' %}" />
{#    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />#}
</head>
<body>
<hr>

<hr>
{% include 'polls/header.html' %}
<div class="jumbotron">
    <div class="container">
        <h1>Please Choose a Question</h1>

    {% block main_content %}
    {% endblock %}
    {% include 'polls/footer.html' %}
    </div>

</div>
</body>
</html>

mysite/polls/templates/polls/detail.html
{%  extends 'polls/base.html' %}

{% block main_content %}

<h2>{{question.question_text}}</h2>

    {% if error_message %} <p><strong>{{ error_message }} </strong></p> {% endif%}

    <form action = "{%  url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value = "{{choice.id}}"/>
            <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label> <br>
    {% endfor %}
    <input type="submit" class = "btn btn-success" value="vote"/>

    </form>
    <a href="{% url 'polls:index' %}"> <<<= Back to Questions</a>

{% endblock %}
<!--
    <ul>
        {% for choice in question.choice_set.all %}
        <li> {{choice.choice_text}} </li>
        {% endfor %}
    </ul>
-->

mysite/polls/templates/polls/footer.html
<footer>
    <p>&copy; 2016 ZeoLearn, INC.</p> {# &copy is another way of calling the copy class #}
</footer>

mysite/polls/templates/polls/header.html
{#view-source:http://getbootstrap.com/examples/theme/#}

<!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">My Django Project</a> {# this is a place for a logo #}
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block main_content %}

{% if latest_questions %}
    <ul>
        {% for question in latest_questions %}
        <!-- here is a basic hard-coded version
        <li><a href="/polls/{{ question.id }}"><b>{{ question.question_text}}</b></a> </li> -->


        <!-- Here we call the URL by referring to its name specified in  polls/urls.py
        In other words we are calling the detail url fro the polls namespace -->

        <li><a href = {% url "polls:detail" question.id %}><b>{{ question.question_text}}</b></a> </li>

        <p> random comment! </p>
        {% endfor %}
    </ul>
{% else %}
   <p> There are no questions. You may add some. </p>
{% endif %}

{% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block main_content %}

    <h1>{{question.question_text}}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
            <!-- merging two tables -->
            <li> {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} </li>
        {% endfor %}
    </ul>

        <a href="{% url 'polls:detail' question.id %}"> Vote Again</a>

{% endblock %}

mysite/root/templates/root/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MySite Portal</title>
</head>
<body>
    <h1>Welcome to the MySite project!</h1>

    <p> Please select one of the options below:</p>

    <h3>Applications</h3>
        <ul>
            <li><a href="{% url 'polls:index' %}"><h4>Polls</h4></a></li>
            <li><a href="{% url 'surveys:index' %}"><h4>Surveys</h4></a></li>
        </ul>
    <br>
    <br>
    <a href="/admin"><h3>Admin Area</h3></a>

</body>
</html>