webstores/musicstore/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload$', views.upload, name='upload'),
    url(r'^browse$', views.browse, name='browse'),
    url(r'^upload/submit$', views.submit, name='submit'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webstores/webstores/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^music/', include('musicstore.urls', namespace='musicstore')),
]

webstores/musicstore/models.py
from django.db import models as m


# Create your models here.
class Genre(m.Model):
    name = m.CharField(max_length=50)

    def __str__(self):
        return self.name

class Category(m.Model):
    name = m.CharField(max_length=50)

    def __str__(self):
        return self.name


class Song(m.Model):
    title = m.CharField(max_length=100)
    artist = m.CharField(max_length=100)
    album = m.CharField(max_length=100, null=True, blank=True)
    desc = m.CharField(max_length=200, null=True, blank=True)
    genre = m.ForeignKey(Genre, on_delete=None)  # one-to-one relationship, where we dont delete anything
    categories = m.ManyToManyField(Category)  # this is a many-to-many relationship
    upload_date = m.DateTimeField('Date Uploaded')
    song_file = m.FileField(upload_to='songs/')

    def __str__(self):
        return self.title

webstores/musicstore/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import *


# Create your views here.
def index(request):
    return render(request, 'musicstore/index.html')


def upload(request):
    genres = Genre.objects.order_by('name')
    categories = Category.objects.all()  # lets try an unordered list
    context = {
        'genres': genres,
        'categories': categories
    }
    return render(request, 'musicstore/upload.html', context)


def submit(request):
    """
    DB API query to create a song (required params only)
    song1=Song(title='Booya', artist='Bob', upload_date=timezone.now(),
    genre=Genre(id=2), song_file='songs/booya.mp3')

    Adding a category:
    c=Category.objects.get(id=1)
    song1.categories.all()
    """


    # Dictionary of all song pa


def browse(request):
    return HttpResponse('<h3>Browse songs here<h3>')

webstores/musicstore/templates/musicstore/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Music Store Portal</title>
</head>
<body>
    <h1>Welcome to the Music Store</h1>

    <p> Please select one of the options below:</p>

    <h3>Applications</h3>
        <ul>
            <li><a href="{% url 'musicstore:upload' %}"><h4>Upload a new Song</h4></a></li>
            <li><a href="{% url 'musicstore:browse' %}"><h4>Browse available songs</h4></a></li>
        </ul>
    <br>
    <br>
{#    <a href="/admin"><h3>Admin Area</h3></a>#}

</body>
</html>

webstores/musicstore/templates/musicstore/upload.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Upload Page</title>
</head>
<body>
    <hr>
        <h1>Upload A New Song</h1>
        <p> Please fill in all the fields below and click Sumbit</p>
    <hr>
    {% if error_message %} <p><strong>{{ error_message }} </strong></p> {% endif%}

    <form action = "{% url 'musicstore:submit' %}" method="post">
        {% csrf_token %}
        <h4>Basic Info</h4>
        <label class="required" for="id_title">Title:</label> <input id="id_title" type="text" name="title" required />
        <br>
        <label class="required" for="id_artist">Artist:</label> <input id="id_artist" type="text" name="artist" required />
        <br>
        Album: <input type="text" name="album" />
        <br>

        <div>
            <h4>Genre:</h4>

            {% for genre in genres %}
                <input type="radio" name="genre" id="genre{{ forloop.counter }}" value = "{{ genre.id }}"/>
                <label for="genre{{ forloop.counter }}">{{ genre.name }}</label>
                <br>
            {% endfor %}
        </div>

        <div>
            <h4>Optional Categories:</h4>

            {% for category in categories %}
                <input type="checkbox" name="{{ forloop.counter }}" value="{{ category.id }}">{{ category.name }}
                <br>
            {% endfor %}
        </div>
        <div>
            <h4>Description (Optional):</h4>
            <p>200 characters max</p>
            <textarea rows="4" cols="25" maxlength="200"
                      placeholder="Add the description here ...">
            </textarea>
        </div>
{#        <div>#}
            <h3>Please Choose the File to Upload</h3>
            <label class="required" for="id_file">Select a file:</label>
            <input id="id_file" type="file" name="song" required />
            <br><br>
            <input type="submit" value="Upload">
{#        </div>#}

    </form>
</body>
</html>